"""DisableRobot Langflow component.

Generated by splitting _internal/rocos_robot_control.py because Langflow discovers one component per file.
"""

"""
ROCOS 机器人基础控制 — Tool 模式。
EnableRobot / DisableRobot / SetWorkMode — 供 LLM Agent 调用。
"""

from langflow.custom import Component

from langflow.io import Output, StrInput, DropdownInput

from langchain_core.tools import Tool

import json as _json

import urllib.error as _urlerror

import urllib.request as _urlreq

from typing import Optional as _Optional

def _rocos_post(_base, _path, _body: dict):
    _url = f"{_base.rstrip('/')}{_path}"
    try:
        _data = _json.dumps(_body).encode("utf-8")
        _req = _urlreq.Request(_url, data=_data, headers={"Content-Type": "application/json", "Accept": "application/json"}, method="POST")
        with _urlreq.urlopen(_req, timeout=30) as _r:
            return _json.loads(_r.read().decode("utf-8"))
    except _urlerror.URLError as _e:
        return {"success": False, "code": -1, "message": f"err: {_e}", "data": None}
    except _json.JSONDecodeError as _e:
        return {"success": False, "code": -2, "message": f"json err: {_e}", "data": None}

WORK_MODES = ["position", "ee_admit_teach", "jnt_admit_teach", "jnt_imp", "cart_imp"]

class DisableRobot(Component):
    display_name: str = "禁用机器人"
    description: str = "全局禁用。Use this to power off."
    icon: str = "PowerOff"; name: str = "disable_robot"
    inputs = [StrInput(name="base_url", value="http://localhost:8080")]
    outputs = [Output(display_name="Tool", name="component_as_tool", method="to_tool", types=["Tool"], tool_mode=True)]

    def to_tool(self) -> Tool:
        base = self.base_url
        def _run(_s: str = "") -> str:
            r = _rocos_post(base, "/api/robot/disable", {})
            return "OK disabled" if r.get("success") else f"FAIL: {r.get('message')}"
        return Tool(name="DisableRobot", description="全局禁用机器人，所有关节下电释放扭矩", func=_run)
