"""GetRobotURDF Langflow component.

Generated by splitting _internal/rocos_robot_state.py because Langflow discovers one component per file.
"""

"""
ROCOS 机器人状态查询组件组 — Tool 模式。

每个组件输出 langchain_core.tools.Tool 对象，供 LLM Agent 直接调用。
工具执行后返回字符串观察值 (Observation)，大模型基于观察值继续推理。
"""

from langflow.custom import Component

from langflow.io import Output, StrInput

from langflow.schema import Data

from langchain_core.tools import Tool

import json as _json

import urllib.error as _urlerror

import urllib.parse as _urlparse

import urllib.request as _urlreq

from typing import Optional as _Optional

def _rocos_get(_base, _path, _params: _Optional[dict] = None):
    _url = f"{_base.rstrip('/')}{_path}"
    if _params:
        _q = "&".join(f"{k}={v}" for k, v in _params.items() if v is not None)
        _url = f"{_url}?{_q}"
    try:
        _req = _urlreq.Request(_url, headers={"Accept": "application/json"})
        with _urlreq.urlopen(_req, timeout=10) as _r:
            return _json.loads(_r.read().decode("utf-8"))
    except _urlerror.URLError as _e:
        return {"success": False, "code": -1, "message": f"网络错误: {_e}", "data": None}
    except _json.JSONDecodeError as _e:
        return {"success": False, "code": -2, "message": f"JSON解析错误: {_e}", "data": None}

def _rocos_post(_base, _path, _body: dict):
    _url = f"{_base.rstrip('/')}{_path}"
    try:
        _data = _json.dumps(_body).encode("utf-8")
        _req = _urlreq.Request(_url, data=_data, headers={"Content-Type": "application/json", "Accept": "application/json"}, method="POST")
        with _urlreq.urlopen(_req, timeout=30) as _r:
            return _json.loads(_r.read().decode("utf-8"))
    except _urlerror.URLError as _e:
        return {"success": False, "code": -1, "message": f"网络错误: {_e}", "data": None}
    except _json.JSONDecodeError as _e:
        return {"success": False, "code": -2, "message": f"JSON解析错误: {_e}", "data": None}

def _rocos_delete(_base, _path, _params: _Optional[dict] = None):
    _url = f"{_base.rstrip('/')}{_path}"
    if _params:
        _q = "&".join(f"{k}={v}" for k, v in _params.items() if v is not None)
        _url = f"{_url}?{_q}"
    try:
        _req = _urlreq.Request(_url, headers={"Accept": "application/json"}, method="DELETE")
        with _urlreq.urlopen(_req, timeout=10) as _r:
            return _json.loads(_r.read().decode("utf-8"))
    except _urlerror.URLError as _e:
        return {"success": False, "code": -1, "message": f"网络错误: {_e}", "data": None}
    except _json.JSONDecodeError as _e:
        return {"success": False, "code": -2, "message": f"JSON解析错误: {_e}", "data": None}

def _rocos_text(_base, _path, _params: _Optional[dict] = None):
    _url = f"{_base.rstrip('/')}{_path}"
    if _params:
        _q = "&".join(f"{k}={v}" for k, v in _params.items() if v is not None)
        _url = f"{_url}?{_q}"
    _req = _urlreq.Request(_url, headers={"Accept": "*/*"})
    with _urlreq.urlopen(_req, timeout=10) as _r:
        return _r.read().decode("utf-8")

def parse_float_list(_text: str, _expected_len: _Optional[int] = None):
    _vals = [float(x.strip()) for x in _text.split(",") if x.strip()]
    if _expected_len is not None and len(_vals) != _expected_len:
        raise ValueError(f"expected {_expected_len} values, got {len(_vals)}")
    return _vals

class GetRobotURDF(Component):
    """获取机器人 URDF 模型 XML"""

    display_name: str = "获取 URDF 模型"
    description: str = (
        "获取 ROCOS 机器人的 URDF 模型 XML。Use this when you need the robot's kinematic tree."
    )
    icon: str = "FileText"
    name: str = "get_robot_urdf"

    inputs = [
        StrInput(name="base_url", display_name="API 基础地址",
                 value="http://localhost:8080"),
    ]

    outputs = [
        Output(display_name="Tool", name="component_as_tool",
               method="to_tool", types=["Tool"], tool_mode=True),
    ]

    def to_tool(self) -> Tool:
        base = self.base_url
        def _run(_input: str = "") -> str:
            r = _rocos_get(base, "/api/robot/urdf")
            if isinstance(r, dict) and not r.get("success", True):
                return f"获取失败: {r.get('message')}"
            return str(r)[:3000]
        return Tool(
            name="GetRobotURDF",
            description="获取机器人URDF模型XML，包含运动学链和连杆信息",
            func=_run,
        )
