"""GetScriptStatus Langflow component.

Generated by splitting _internal/rocos_script.py because Langflow discovers one component per file.
"""

"""ROCOS Lua脚本管理 — Tool 模式。6个脚本管理组件"""

from langflow.custom import Component

from langflow.io import Output, StrInput

from langchain_core.tools import Tool

import json as _json

import urllib.request as _urlreq

def _post(b,p,d):
    bd=_json.dumps(d).encode()
    with _urlreq.urlopen(_urlreq.Request(f"{b.rstrip('/')}{p}",data=bd,headers={"Content-Type":"application/json","Accept":"application/json"},method="POST"),timeout=30) as r:
        return _json.loads(r.read().decode("utf-8"))

def _get(b,p):
    with _urlreq.urlopen(_urlreq.Request(f"{b.rstrip('/')}{p}",headers={"Accept":"application/json"}),timeout=10) as r:
        return _json.loads(r.read().decode("utf-8"))

BI=[StrInput(name="base_url",value="http://localhost:8080")]

TO=lambda m: [Output(display_name="Tool",name="component_as_tool",method=m,types=["Tool"],tool_mode=True)]

class GetScriptStatus(Component):
    display_name="查询脚本状态"; icon="Eye"; name="get_script_status"; inputs=BI; outputs=TO("to_tool")
    def to_tool(self)->Tool:
        b=self.base_url
        def _run(_s=""): r=_get(b,"/api/script/status"); d=r.get("data",{}); return f"id={d.get('script_id')} state={d.get('state')} file={d.get('filename')} line={d.get('line')}" if r.get("success") else f"FAIL: {r.get('message')}"
        return Tool(name="GetScriptStatus",description="查询当前Lua脚本的执行状态",func=_run)
