"""JogStop Langflow component.

Generated by splitting _internal/rocos_jogging.py because Langflow discovers one component per file.
"""

"""ROCOS 点动控制 — Tool 模式。JogStart / JogStop"""

from langflow.custom import Component

from langflow.io import Output, StrInput, DropdownInput, FloatInput

from langchain_core.tools import Tool

import json as _json

import urllib.request as _urlreq

def _post(b, p, d):
    bd = _json.dumps(d).encode()
    r = _urlreq.Request(f"{b.rstrip('/')}{p}", data=bd, headers={"Content-Type":"application/json","Accept":"application/json"}, method="POST")
    with _urlreq.urlopen(r, timeout=30) as rr:
        return _json.loads(rr.read().decode("utf-8"))

JOG_FLAGS = ["J0","J1","J2","J3","J4","J5","J6","TOOL_X","TOOL_Y","TOOL_Z","TOOL_ROLL","TOOL_PITCH","TOOL_YAW","FLANGE_X","FLANGE_Y","FLANGE_Z","FLANGE_ROLL","FLANGE_PITCH","FLANGE_YAW","OBJECT_X","OBJECT_Y","OBJECT_Z","OBJECT_ROLL","OBJECT_PITCH","OBJECT_YAW","BASE_X","BASE_Y","BASE_Z","BASE_ROLL","BASE_PITCH","BASE_YAW","NULLSPACE"]

DIRS = ["POSITIVE","NEGATIVE","NONE"]

class JogStop(Component):
    display_name: str = "停止点动"
    description: str = "停止所有点动。Use this to stop jogging."
    icon: str = "MousePointer"; name: str = "jog_stop"
    inputs = [StrInput(name="base_url", value="http://localhost:8080")]
    outputs = [Output(display_name="Tool", name="component_as_tool", method="to_tool", types=["Tool"], tool_mode=True)]
    def to_tool(self) -> Tool:
        base = self.base_url
        return Tool(name="JogStop", description="停止所有点动/拖拽运动", func=lambda _s="": "OK" if _post(base,"/api/robot/jog/stop",{}).get("success") else "FAIL")
