"""JogStart Langflow component.

Generated by splitting _internal/rocos_jogging.py because Langflow discovers one component per file.
"""

"""ROCOS 点动控制 — Tool 模式。JogStart / JogStop"""

from langflow.custom import Component

from langflow.io import Output, StrInput, DropdownInput, FloatInput

from langchain_core.tools import Tool

import json as _json

import urllib.request as _urlreq

def _parse_input(s):
    """解析 LLM 输入: 支持裸字符串或 JSON {\"__arg1\": \"...\"}"""
    raw = s.strip()
    if not raw:
        return ""
    # Agent tool calling 可能传 JSON: {"__arg1": "dim_speeds=0.3, timeout=2.0"}
    if raw.startswith("{"):
        try:
            obj = _json.loads(raw)
            if isinstance(obj, dict):
                for v in obj.values():
                    if isinstance(v, str) and v.strip():
                        return v.strip()
        except Exception:
            pass
    return raw

def _parse_kv_args(s: str):
    args = {}
    modes = []
    for part in s.replace(",", " ").split():  # 逗号也当分隔符
        if "=" in part:
            k, v = part.split("=", 1)
            args[k.strip().lower()] = v.strip().rstrip(",")
        elif part.strip():
            modes.append(part.strip().lower())
    return modes, args

def _parse_vec(text: str):
    return [float(x.strip()) for x in text.replace("，", ",").split(",") if x.strip()]

def _post(b, p, d):
    bd = _json.dumps(d).encode()
    r = _urlreq.Request(f"{b.rstrip('/')}{p}", data=bd, headers={"Content-Type":"application/json","Accept":"application/json"}, method="POST")
    with _urlreq.urlopen(r, timeout=30) as rr:
        return _json.loads(rr.read().decode("utf-8"))

JOG_FLAGS = ["J0","J1","J2","J3","J4","J5","J6","TOOL_X","TOOL_Y","TOOL_Z","TOOL_ROLL","TOOL_PITCH","TOOL_YAW","FLANGE_X","FLANGE_Y","FLANGE_Z","FLANGE_ROLL","FLANGE_PITCH","FLANGE_YAW","OBJECT_X","OBJECT_Y","OBJECT_Z","OBJECT_ROLL","OBJECT_PITCH","OBJECT_YAW","BASE_X","BASE_Y","BASE_Z","BASE_ROLL","BASE_PITCH","BASE_YAW","NULLSPACE"]

DIRS = ["POSITIVE","NEGATIVE","NONE"]

class JogStart(Component):
    display_name: str = "启动点动"
    description: str = "零空间/关节/笛卡尔点动。默认svd零空间(dim_speeds=[speed])，最简单"
    icon: str = "MousePointerClick"; name: str = "jog_start"
    inputs = [
        StrInput(name="base_url", value="http://localhost:8080"),
        DropdownInput(name="flag", display_name="默认方向", options=JOG_FLAGS, value="NULLSPACE"),
        DropdownInput(name="direction", options=DIRS, value="POSITIVE"),
        FloatInput(name="max_speed", value=0.3), FloatInput(name="timeout_s", value=2.0),
    ]
    outputs = [Output(display_name="Tool", name="component_as_tool", method="to_tool", types=["Tool"], tool_mode=True)]
    def to_tool(self) -> Tool:
        base, flag, dire, spd, to = self.base_url, self.flag, self.direction, self.max_speed, self.timeout_s
        def _run(s: str = "") -> str:
            f, d = flag, dire; speed, timeout = spd, to
            s = _parse_input(s)  # 处理 JSON wrapper
            modes, args = _parse_kv_args(s)
            # 读取参数覆盖
            if "flag" in args: f = args["flag"]
            if "direction" in args: d = args["direction"]
            if "speed" in args: speed = float(args["speed"])
            if "timeout" in args: timeout = float(args["timeout"])

            # 判断是否为 SVD 零空间（默认）
            explicit_svd = "svd" in modes
            explicit_nullspace = "nullspace" in modes
            is_default = f == "NULLSPACE" and not explicit_nullspace

            if explicit_svd or is_default:
                dim_speed = float(args.get("dim_speeds", speed))
                try: vec_num = float(s.strip()) if s.strip() else None
                except: vec_num = None
                if vec_num is not None:
                    dim_speed = vec_num  # 纯数字输入 = 零空间速度
                r = _post(base, "/api/robot/jog/svd", {"dim_speeds": [dim_speed], "timeout": timeout})
                return f"SVD nullspace OK (speed={dim_speed})" if r.get("success") else f"SVD FAIL: {r.get('message')}"

            # nullspace 向量模式
            if explicit_nullspace:
                vec_text = args.get("joints") or args.get("joints_vec") or args.get("nullspace_vec")
                if not vec_text: return "nullspace 需要 joints=向量"
                vec = _parse_vec(vec_text)
                r = _post(base, "/api/robot/jog/nullspace", {"joints": vec, "direction": d, "speed": speed, "timeout": timeout})
                return f"Nullspace OK ({vec[:3]}...)" if r.get("success") else f"Nullspace FAIL: {r.get('message')}"

            # flag / 向量接口
            if f in JOG_FLAGS:
                r = _post(base, "/api/robot/jog", {"flag": f, "direction": d, "max_speed": speed, "timeout": timeout})
            else:
                vec = _parse_vec(f)
                r = _post(base, "/api/robot/jog/joint", {"joints": vec, "direction": d, "speed": speed, "timeout": timeout})
            return f"Jog OK ({f} {d})" if r.get("success") else f"Jog FAIL: {r.get('message')}"
        return Tool(name="JogStart",
            description="默认SVD零空间(末端不动关节重配置)。输入dim_speeds=0.3控制速度，timeout=2.0控制时长。也支持flag关节/笛卡尔点动",
            func=_run)
