"""LoadFrames Langflow component.

Generated by splitting _internal/rocos_frames.py because Langflow discovers one component per file.
"""

"""ROCOS 坐标系管理 — Tool 模式。12个工具/工件坐标系组件"""

from langflow.custom import Component

from langflow.io import Output, StrInput

from langchain_core.tools import Tool

import json as _json

import urllib.request as _urlreq

def _get(b,p,pa=None):
    u=f"{b.rstrip('/')}{p}"
    if pa: u+="?"+"&".join(f"{k}={v}" for k,v in pa.items() if v is not None)
    with _urlreq.urlopen(_urlreq.Request(u,headers={"Accept":"application/json"}),timeout=10) as r:
        return _json.loads(r.read().decode("utf-8"))

def _post(b,p,d):
    bd=_json.dumps(d).encode()
    with _urlreq.urlopen(_urlreq.Request(f"{b.rstrip('/')}{p}",data=bd,headers={"Content-Type":"application/json","Accept":"application/json"},method="POST"),timeout=30) as r:
        return _json.loads(r.read().decode("utf-8"))

def _del(b,p,pa=None):
    u=f"{b.rstrip('/')}{p}"
    if pa: u+="?"+"&".join(f"{k}={v}" for k,v in pa.items() if v is not None)
    with _urlreq.urlopen(_urlreq.Request(u,headers={"Accept":"application/json"},method="DELETE"),timeout=10) as r:
        return _json.loads(r.read().decode("utf-8"))

BASE_INPUT = [StrInput(name="base_url", value="http://localhost:8080")]

FRAME_INPUT = lambda: [StrInput(name="base_url", value="http://localhost:8080"), StrInput(name="name", display_name="坐标系名称", value="default")]

POSE_INPUT = lambda: [StrInput(name="base_url", value="http://localhost:8080"), StrInput(name="name", value="default"), StrInput(name="pos_x", value="0"), StrInput(name="pos_y", value="0"), StrInput(name="pos_z", value="0"), StrInput(name="ori_x", value="0"), StrInput(name="ori_y", value="0"), StrInput(name="ori_z", value="0"), StrInput(name="ori_w", value="1")]

PATH_INPUT = lambda: [StrInput(name="base_url", value="http://localhost:8080"), StrInput(name="path", display_name="YAML文件路径", value="frames.yaml")]

TOOL_OUT = lambda m: [Output(display_name="Tool", name="component_as_tool", method=m, types=["Tool"], tool_mode=True)]

class LoadFrames(Component):
    display_name="加载坐标系"; description="从YAML文件加载坐标系"; icon="Upload"; name="load_frames"; inputs=PATH_INPUT(); outputs=TOOL_OUT("to_tool")
    def to_tool(self)->Tool:
        b,p=self.base_url,self.path
        def _run(_s=""): r=_post(b,"/api/robot/frames/load",{"path":p}); return f"OK loaded {p}" if r.get("success") else f"FAIL: {r.get('message')}"
        return Tool(name="LoadFrames",description=f"从YAML文件'{p}'加载坐标系",func=_run)
