"""MotionResume Langflow component.

Generated by splitting _internal/rocos_motion.py because Langflow discovers one component per file.
"""

"""
ROCOS 运动控制 — Tool 模式。
MoveJ / MoveL / Stop / Pause / Resume / Status / WaitMove
"""

from langflow.custom import Component

from langflow.io import Output, StrInput, FloatInput

from langchain_core.tools import Tool

import json as _json

import urllib.error as _urlerror

import urllib.request as _urlreq

from typing import Optional as _Optional

def _rocos_get(_base, _path, _params=None):
    _url = f"{_base.rstrip('/')}{_path}"
    if _params: _url += "?" + "&".join(f"{k}={v}" for k, v in _params.items() if v is not None)
    try:
        _req = _urlreq.Request(_url, headers={"Accept": "application/json"})
        with _urlreq.urlopen(_req, timeout=10) as _r:
            return _json.loads(_r.read().decode("utf-8"))
    except Exception as _e:
        return {"success": False, "code": -1, "message": str(_e)}

def _rocos_post(_base, _path, _body: dict):
    try:
        _data = _json.dumps(_body).encode("utf-8")
        _req = _urlreq.Request(f"{_base.rstrip('/')}{_path}", data=_data, headers={"Content-Type":"application/json","Accept":"application/json"}, method="POST")
        with _urlreq.urlopen(_req, timeout=30) as _r:
            return _json.loads(_r.read().decode("utf-8"))
    except Exception as _e:
        return {"success": False, "code": -1, "message": str(_e)}

class MotionResume(Component):
    display_name: str = "继续运动"
    description: str = "继续暂停的运动。Use this to resume."
    icon: str = "PlayCircle"; name: str = "motion_resume"
    inputs = [StrInput(name="base_url", value="http://localhost:8080")]
    outputs = [Output(display_name="Tool", name="component_as_tool", method="to_tool", types=["Tool"], tool_mode=True)]

    def to_tool(self) -> Tool:
        base = self.base_url
        def _run(_s: str = "") -> str:
            r = _rocos_post(base, "/api/robot/resume", {})
            return "OK resumed" if r.get("success") else f"Resume FAIL: {r.get('message')}"
        return Tool(name="MotionResume", description="继续之前暂停的运动", func=_run)
