"""MoveJ Langflow component.

Generated by splitting _internal/rocos_motion.py because Langflow discovers one component per file.
"""

"""
ROCOS 运动控制 — Tool 模式。
MoveJ / MoveL / Stop / Pause / Resume / Status / WaitMove
"""

from langflow.custom import Component

from langflow.io import Output, StrInput, FloatInput

from langchain_core.tools import Tool

import json as _json

import urllib.error as _urlerror

import urllib.request as _urlreq

from typing import Optional as _Optional

def _rocos_get(_base, _path, _params=None):
    _url = f"{_base.rstrip('/')}{_path}"
    if _params: _url += "?" + "&".join(f"{k}={v}" for k, v in _params.items() if v is not None)
    try:
        _req = _urlreq.Request(_url, headers={"Accept": "application/json"})
        with _urlreq.urlopen(_req, timeout=10) as _r:
            return _json.loads(_r.read().decode("utf-8"))
    except Exception as _e:
        return {"success": False, "code": -1, "message": str(_e)}

def _rocos_post(_base, _path, _body: dict):
    try:
        _data = _json.dumps(_body).encode("utf-8")
        _req = _urlreq.Request(f"{_base.rstrip('/')}{_path}", data=_data, headers={"Content-Type":"application/json","Accept":"application/json"}, method="POST")
        with _urlreq.urlopen(_req, timeout=30) as _r:
            return _json.loads(_r.read().decode("utf-8"))
    except Exception as _e:
        return {"success": False, "code": -1, "message": str(_e)}

class MoveJ(Component):
    display_name: str = "MoveJ 关节运动"
    description: str = "关节空间运动。LLM调用时输入: joints角度(逗号分隔7个值) speed=速度"
    icon: str = "Move"; name: str = "move_j"
    inputs = [
        StrInput(name="base_url", value="http://localhost:8080"),
        StrInput(name="joints", display_name="默认关节角度", value="0.1,0.8,0.1,0.3,0.4,0.5,0.6"),
        FloatInput(name="velocity", value=0.3), FloatInput(name="acceleration", value=1.0),
    ]
    outputs = [Output(display_name="Tool", name="component_as_tool", method="to_tool", types=["Tool"], tool_mode=True)]

    def to_tool(self) -> Tool:
        base, vel, acc = self.base_url, self.velocity, self.acceleration
        def _run(input_str: str = "") -> str:
            joints_str = input_str.strip() if input_str.strip() else self.joints  # fallback
            speed = vel
            if "speed=" in joints_str:
                parts = joints_str.split("speed=")
                joints_str = parts[0].strip()
                try: speed = float(parts[1].strip().split()[0])
                except: pass
            try: joints = [float(x.strip()) for x in joints_str.replace("，",",").split(",") if x.strip()]
            except: return "参数错误: joints格式应为逗号分隔的数值"
            r = _rocos_post(base, "/api/robot/movej", {"joints": joints, "velocity": speed, "acceleration": acc})
            if r.get("success"): return f"MoveJ accepted → {r.get('data',{}).get('robot_state','RUNNING')}"
            return f"MoveJ FAIL (code={r.get('code')}): {r.get('message')}"
        return Tool(name="MoveJ", description="关节空间运动。输入7个目标关节角度(逗号分隔,弧度)，可选speed=速度。例: 0,0.9,0,1.5,0,-1,0 speed=0.3", func=_run)
