"""MoveL Langflow component.

Generated by splitting _internal/rocos_motion.py because Langflow discovers one component per file.
"""

"""
ROCOS 运动控制 — Tool 模式。
MoveJ / MoveL / Stop / Pause / Resume / Status / WaitMove
"""

from langflow.custom import Component

from langflow.io import Output, StrInput, FloatInput

from langchain_core.tools import Tool

import json as _json

import urllib.error as _urlerror

import urllib.request as _urlreq

from typing import Optional as _Optional

def _rocos_get(_base, _path, _params=None):
    _url = f"{_base.rstrip('/')}{_path}"
    if _params: _url += "?" + "&".join(f"{k}={v}" for k, v in _params.items() if v is not None)
    try:
        _req = _urlreq.Request(_url, headers={"Accept": "application/json"})
        with _urlreq.urlopen(_req, timeout=10) as _r:
            return _json.loads(_r.read().decode("utf-8"))
    except Exception as _e:
        return {"success": False, "code": -1, "message": str(_e)}

def _rocos_post(_base, _path, _body: dict):
    try:
        _data = _json.dumps(_body).encode("utf-8")
        _req = _urlreq.Request(f"{_base.rstrip('/')}{_path}", data=_data, headers={"Content-Type":"application/json","Accept":"application/json"}, method="POST")
        with _urlreq.urlopen(_req, timeout=30) as _r:
            return _json.loads(_r.read().decode("utf-8"))
    except Exception as _e:
        return {"success": False, "code": -1, "message": str(_e)}

class MoveL(Component):
    display_name: str = "MoveL 直线运动"
    description: str = "笛卡尔直线运动。LLM调用时输入: x,y,z qx,qy,qz,qw speed=速度"
    icon: str = "MoveDiagonal"; name: str = "move_l"
    inputs = [
        StrInput(name="base_url", value="http://localhost:8080"),
        FloatInput(name="velocity", value=0.15),
    ]
    outputs = [Output(display_name="Tool", name="component_as_tool", method="to_tool", types=["Tool"], tool_mode=True)]

    def to_tool(self) -> Tool:
        base, vel = self.base_url, self.velocity
        def _run(input_str: str = "") -> str:
            s = input_str.strip()
            speed = vel
            if "speed=" in s:
                parts = s.split("speed="); s = parts[0].strip()
                try: speed = float(parts[1].strip().split()[0])
                except: pass
            vals = [float(x.strip()) for x in s.replace("，",",").split(",") if x.strip()]
            if len(vals) < 3: return "参数错误: 需要 x,y,z 或 x,y,z,qx,qy,qz,qw"
            pos = {"x": vals[0], "y": vals[1], "z": vals[2]}
            ori = {"x": vals[3] if len(vals)>3 else 0, "y": vals[4] if len(vals)>4 else 0, "z": vals[5] if len(vals)>5 else 0, "w": vals[6] if len(vals)>6 else 1}
            r = _rocos_post(base, "/api/robot/movel", {"pose": {"position": pos, "orientation": ori}, "velocity": speed})
            if r.get("success"): return f"MoveL accepted → {r.get('data',{}).get('robot_state','RUNNING')}"
            return f"MoveL FAIL (code={r.get('code')}): {r.get('message')}"
        return Tool(name="MoveL", description="笛卡尔直线运动。输入目标位姿 x,y,z,qx,qy,qz,qw speed=速度。例: -0.8,0,0.3,0,-0.707,0,0.707 speed=0.15", func=_run)
