"""ResetRobotFault Langflow component.

Generated by splitting _internal/rocos_agent.py because Langflow discovers one component per file.
"""

"""
ROCOS 语义层组件 — 将实战中迭代出的控制模式编码为可复用组件。

包含:
  - RocosAgentPrompt: 生成最优的 Agent 系统提示词
  - RocosErrorRecovery: 自动错误恢复
  - RocosSafeMoveL: 先读状态再执行 MoveL 的安全模式
  - ResetRobotFault: 复位机器人 Fault（POST /api/robot/reset）
"""

from langflow.custom import Component

from langflow.io import Output, StrInput, FloatInput, DropdownInput

from langflow.schema import Data, Message

from langchain_core.tools import Tool

import json

import urllib.error

import urllib.parse

import urllib.request

from typing import Optional

def _error(code: int, message: str) -> dict:
    return {"success": False, "code": code, "message": message, "data": None}

def _url(base_url: str, path: str, params: Optional[dict] = None) -> str:
    url = f"{base_url.rstrip('/')}{path}"
    if params:
        query = urllib.parse.urlencode({k: v for k, v in params.items() if v is not None})
        if query:
            url = f"{url}?{query}"
    return url

def _decode_json(body: str) -> dict:
    if not body:
        return {}
    return json.loads(body)

def _parse_http_error(e: urllib.error.HTTPError) -> dict:
    try:
        body = e.read().decode("utf-8")
        parsed = _decode_json(body)
        if isinstance(parsed, dict):
            parsed.setdefault("success", False)
            parsed.setdefault("code", e.code)
            parsed.setdefault("message", e.reason)
            return parsed
    except Exception:
        pass
    return _error(e.code, f"HTTP {e.code}: {e.reason}")

def _rocos_request(
    base_url: str, path: str, method: str = "GET",
    body: Optional[dict] = None, params: Optional[dict] = None,
    expect_json: bool = True, timeout: float = 30.0,
):
    url = _url(base_url, path, params)
    data = json.dumps(body).encode("utf-8") if body is not None else None
    headers = {"Accept": "application/json" if expect_json else "*/*"}
    if data is not None:
        headers["Content-Type"] = "application/json"
    try:
        req = urllib.request.Request(url, data=data, headers=headers, method=method)
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            text = resp.read().decode("utf-8")
            return _decode_json(text) if expect_json else text
    except urllib.error.HTTPError as e:
        return _parse_http_error(e)
    except urllib.error.URLError as e:
        return _error(-1, f"网络错误: {e}")
    except json.JSONDecodeError as e:
        return _error(-2, f"JSON 解析错误: {e}")

def _rocos_get(base_url: str, path: str, params: Optional[dict] = None) -> dict:
    return _rocos_request(base_url, path, method="GET", params=params, timeout=10.0)

def _rocos_post(base_url: str, path: str, body: Optional[dict] = None) -> dict:
    return _rocos_request(base_url, path, method="POST", body=body or {})

def _rocos_delete(base_url: str, path: str, params: Optional[dict] = None) -> dict:
    return _rocos_request(base_url, path, method="DELETE", params=params)

def _rocos_text(base_url: str, path: str, params: Optional[dict] = None) -> str:
    return _rocos_request(base_url, path, method="GET", params=params, expect_json=False, timeout=10.0)

def parse_float_list(text: str, expected_len: Optional[int] = None) -> list[float]:
    values = [float(x.strip()) for x in text.split(",") if x.strip()]
    if expected_len is not None and len(values) != expected_len:
        raise ValueError(f"expected {expected_len} values, got {len(values)}")
    return values

DEFAULT_MEMORY_DIR = "/tmp/rocos_memory"

DEFAULT_MEMORY_FILE = "rocos_memory.json"

def _record_to_memory(memory_dir: str, entry: dict, intent: str = "", action_template: dict = None):
    """记录执行记忆 + 同步语义缓存（数据与 MemoryStore.cache_learn 兼容）"""
    import os as _os
    fpath = _os.path.join(memory_dir, DEFAULT_MEMORY_FILE)
    _os.makedirs(_os.path.dirname(fpath), exist_ok=True)
    if _os.path.exists(fpath):
        with open(fpath) as f:
            mem = json.load(f)
    else:
        mem = {"executions": [], "patterns": [], "semantic_cache": {},
               "stats": {"total_motions": 0, "errors": 0, "recoveries": 0}}

    # 1. 写执行记录（包含 before/after 状态, error_code）
    entry.setdefault("timestamp", time.strftime("%Y-%m-%dT%H:%M:%S"))
    mem.setdefault("executions", []).append(entry)
    if len(mem["executions"]) > 200:
        mem["executions"] = mem["executions"][-200:]

    # 2. 更新统计
    mem["stats"]["total_motions"] = mem["stats"].get("total_motions", 0) + 1
    if not entry.get("success", True):
        mem["stats"]["errors"] = mem["stats"].get("errors", 0) + 1

    # 3. 语义缓存学习（与 MemoryStore.cache_learn 相同格式）
    if intent and action_template:
        sc = mem.setdefault("semantic_cache", {})
        cache_key = intent.lower().replace(" ", "")
        ts = entry.get("timestamp", time.strftime("%Y-%m-%dT%H:%M:%S"))
        template_key = json.dumps(action_template, sort_keys=True)
        success = entry.get("success", True)

        if cache_key in sc and isinstance(sc[cache_key], dict):
            existing = sc[cache_key]
            if json.dumps(existing.get("action", {}), sort_keys=True) == template_key:
                existing["frequency"] = existing.get("frequency", 0) + 1
                if success:
                    existing["success_count"] = existing.get("success_count", 0) + 1
                else:
                    existing["failure_count"] = existing.get("failure_count", 0) + 1
                existing["last_used"] = ts
            else:
                existing["frequency"] = existing.get("frequency", 0) + 1
                existing["action"] = action_template
                if success:
                    existing["success_count"] = existing.get("success_count", 0) + 1
                else:
                    existing["failure_count"] = existing.get("failure_count", 0) + 1
        else:
            sc[cache_key] = {
                "action_name": "safe_executor",
                "action": action_template,
                "frequency": 1,
                "success_count": 1 if success else 0,
                "failure_count": 0 if success else 1,
                "first_seen": ts,
                "last_used": ts,
            }

    with open(fpath, 'w') as f:
        json.dump(mem, f, indent=2, ensure_ascii=False)

class ResetRobotFault(Component):
    """复位机器人 Fault — POST /api/robot/reset"""

    display_name: str = "复位机器人"
    description: str = (
        "复位机器人 Fault 状态。调用 POST /api/robot/reset。"
        "FSM: ERROR_STATE + EventResetReq → RESETTING → EventEnabled → STOPPED。"
        "Use this tool to reset the robot after an execution fault."
    )
    icon: str = "RotateCcw"
    name: str = "reset_robot_fault"

    inputs = [
        StrInput(name="base_url", display_name="API 基础地址", value="http://localhost:8080"),
    ]

    outputs = [
        Output(display_name="Reset Result", name="result", method="reset",
            tool_mode=True),
    ]

    def reset(self) -> Data:
        import time
        base = self.base_url.rstrip("/")

        state = _rocos_get(base, "/api/robot/state")
        robot_state = state.get("data", {}).get("robot_state", "UNKNOWN")

        if robot_state == "STOPPED":
            return Data(text="机器人已在 STOPPED，无需复位", data={"reset": False})

        result = _rocos_post(base, "/api/robot/reset", {})
        if not result.get("success"):
            return Data(
                text=f"❌ Reset 失败: {result.get('message')}",
                data={"reset": False},
            )

        for _ in range(10):
            time.sleep(0.5)
            s = _rocos_get(base, "/api/robot/state")
            st = s.get("data", {}).get("robot_state", "UNKNOWN")
            if st == "STOPPED":
                text = "✅ 复位成功 → STOPPED"
                self.status = text
                return Data(text=text, data={"reset": True, "state": "STOPPED"})

        text = "⚠️ 复位等待超时"
        self.status = text
        return Data(text=text, data={"reset": False})
