"""RocosReflect Langflow component.

Generated by splitting _internal/rocos_memory.py because Langflow discovers one component per file.
"""

"""
ROCOS 自进化记忆系统 — 越用越聪明，越用越快

四层闭环:
  1. RocosSemanticCache — 语义→指令缓存 (高频指令跳过LLM，响应 8s→0.5s)
  2. RocosMemory        — 记录每次动作 (执行记忆)
  3. RocosReflect       — 分析历史提取模式 (自省)
  4. RocosKnowledge     — 累积可查询的经验规则 (知识库)

存储后端: 本地 JSON 文件 (零外部依赖)
路径: {memory_dir}/rocos_memory.json  (默认 /tmp/rocos_memory/rocos_memory.json)
"""

import json

import os

import time

from pathlib import Path

from typing import Optional

from langflow.custom import Component

from langflow.io import Output, StrInput, FloatInput

from langflow.schema import Data

from langchain_core.tools import Tool

import json

import urllib.error

import urllib.parse

import urllib.request

from typing import Optional

def _error(code: int, message: str) -> dict:
    return {"success": False, "code": code, "message": message, "data": None}

def _url(base_url: str, path: str, params: Optional[dict] = None) -> str:
    url = f"{base_url.rstrip('/')}{path}"
    if params:
        query = urllib.parse.urlencode({k: v for k, v in params.items() if v is not None})
        if query:
            url = f"{url}?{query}"
    return url

def _decode_json(body: str) -> dict:
    if not body:
        return {}
    return json.loads(body)

def _parse_http_error(e: urllib.error.HTTPError) -> dict:
    try:
        body = e.read().decode("utf-8")
        parsed = _decode_json(body)
        if isinstance(parsed, dict):
            parsed.setdefault("success", False)
            parsed.setdefault("code", e.code)
            parsed.setdefault("message", e.reason)
            return parsed
    except Exception:
        pass
    return _error(e.code, f"HTTP {e.code}: {e.reason}")

def _rocos_request(
    base_url: str, path: str, method: str = "GET",
    body: Optional[dict] = None, params: Optional[dict] = None,
    expect_json: bool = True, timeout: float = 30.0,
):
    url = _url(base_url, path, params)
    data = json.dumps(body).encode("utf-8") if body is not None else None
    headers = {"Accept": "application/json" if expect_json else "*/*"}
    if data is not None:
        headers["Content-Type"] = "application/json"
    try:
        req = urllib.request.Request(url, data=data, headers=headers, method=method)
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            text = resp.read().decode("utf-8")
            return _decode_json(text) if expect_json else text
    except urllib.error.HTTPError as e:
        return _parse_http_error(e)
    except urllib.error.URLError as e:
        return _error(-1, f"网络错误: {e}")
    except json.JSONDecodeError as e:
        return _error(-2, f"JSON 解析错误: {e}")

def _rocos_get(base_url: str, path: str, params: Optional[dict] = None) -> dict:
    return _rocos_request(base_url, path, method="GET", params=params, timeout=10.0)

def _rocos_post(base_url: str, path: str, body: Optional[dict] = None) -> dict:
    return _rocos_request(base_url, path, method="POST", body=body or {})

def _rocos_delete(base_url: str, path: str, params: Optional[dict] = None) -> dict:
    return _rocos_request(base_url, path, method="DELETE", params=params)

def _rocos_text(base_url: str, path: str, params: Optional[dict] = None) -> str:
    return _rocos_request(base_url, path, method="GET", params=params, expect_json=False, timeout=10.0)

def parse_float_list(text: str, expected_len: Optional[int] = None) -> list[float]:
    values = [float(x.strip()) for x in text.split(",") if x.strip()]
    if expected_len is not None and len(values) != expected_len:
        raise ValueError(f"expected {expected_len} values, got {len(values)}")
    return values

DEFAULT_MEMORY_DIR = "/tmp/rocos_memory"

DEFAULT_MEMORY_FILE = "rocos_memory.json"

class MemoryStore:
    """本地 JSON 文件存储，零依赖"""

    def __init__(self, filepath: str):
        self.filepath = filepath
        Path(os.path.dirname(filepath)).mkdir(parents=True, exist_ok=True)
        if not os.path.exists(filepath):
            self._save({"executions": [], "patterns": [], "stats": {
                "total_motions": 0, "errors": 0, "recoveries": 0,
                "total_distance": 0.0, "favored_positions": [],
            }})

    def _load(self) -> dict:
        try:
            with open(self.filepath) as f:
                return json.load(f)
        except (json.JSONDecodeError, FileNotFoundError):
            return {"executions": [], "patterns": [], "stats": {}}

    def _save(self, data: dict):
        with open(self.filepath, 'w') as f:
            json.dump(data, f, indent=2, ensure_ascii=False)

    def record(self, entry: dict):
        data = self._load()
        data["executions"].append(entry)
        # 只保留最近 200 条
        if len(data["executions"]) > 200:
            data["executions"] = data["executions"][-200:]
        # 更新统计
        stats = data.setdefault("stats", {})
        stats["total_motions"] = stats.get("total_motions", 0) + 1
        if not entry.get("success", True):
            stats["errors"] = stats.get("errors", 0) + 1
        self._save(data)

    def record_recovery(self):
        data = self._load()
        stats = data.setdefault("stats", {})
        stats["recoveries"] = stats.get("recoveries", 0) + 1
        self._save(data)

    def get_recent(self, n: int = 10) -> list:
        data = self._load()
        return data["executions"][-n:]

    def get_stats(self) -> dict:
        return self._load().get("stats", {})

    def add_pattern(self, pattern: dict):
        data = self._load()
        # 去重: 如果已存在相似 pattern 则更新置信度
        for p in data["patterns"]:
            if p.get("name") == pattern.get("name"):
                p["confidence"] = min(1.0, p.get("confidence", 0.5) + 0.15)
                p["count"] = p.get("count", 1) + 1
                self._save(data)
                return
        pattern["count"] = 1
        data["patterns"].append(pattern)
        self._save(data)

    def get_patterns(self) -> list:
        return self._load().get("patterns", [])

    # ---- 语义缓存 ----

    def cache_query(self, intent: str) -> Optional[dict]:
        """查询语义缓存: 命中返回 {action_name, action(template), frequency, confidence, cached}, 否则 None"""
        intent_key = self._normalize_intent(intent)
        data = self._load()
        cache = data.setdefault("semantic_cache", {})

        if intent_key in cache:
            entry = cache[intent_key]
            freq = entry.get("frequency", 0)
            if freq >= 3:
                return {
                    "action_name": entry.get("action_name", ""),
                    "action": entry.get("action", {}),
                    "frequency": freq,
                    "success_count": entry.get("success_count", 0),
                    "failure_count": entry.get("failure_count", 0),
                    "confidence": min(0.99, 0.5 + freq * 0.1),
                    "cached": True,
                }
        return None

    def cache_learn(self, intent: str, action_name: str = "", action_template: Optional[dict] = None,
                     success: bool = True, before_state: Optional[dict] = None, after_state: Optional[dict] = None,
                     error_code: Optional[int] = None):
        """学习: 记录语义→动作模板 + 同步写执行记录

        action_template 格式:
          {"type": "cartesian_delta", "delta": [0, 0.03, 0, 0, 0, 0], "speed": 0.1}
        before_state/after_state: 可选，有则同时写 executions 记录
        """
        intent_key = self._normalize_intent(intent)
        data = self._load()
        cache = data.setdefault("semantic_cache", {})
        ts = time.strftime("%Y-%m-%dT%H:%M:%S")

        template = action_template or {}
        template_key = json.dumps(template, sort_keys=True)

        # 更新缓存
        if intent_key in cache and isinstance(cache[intent_key], dict):
            existing = cache[intent_key]
            existing_template = existing.get("action", {})
            if json.dumps(existing_template, sort_keys=True) == template_key:
                existing["frequency"] = existing.get("frequency", 0) + 1
                if success:
                    existing["success_count"] = existing.get("success_count", 0) + 1
                else:
                    existing["failure_count"] = existing.get("failure_count", 0) + 1
                existing["last_used"] = ts
            else:
                if existing.get("frequency", 0) < 2:
                    existing["action"] = template
                    existing["action_name"] = action_name
                    existing["frequency"] = 1
                    existing["success_count"] = 1 if success else 0
                    existing["failure_count"] = 0 if success else 1
        else:
            cache[intent_key] = {
                "action_name": action_name,
                "action": template,
                "frequency": 1,
                "success_count": 1 if success else 0,
                "failure_count": 0 if success else 1,
                "first_seen": ts,
                "last_used": ts,
            }

        # 同步写执行记录
        if before_state is not None:
            entry = {
                "timestamp": ts,
                "action": action_name,
                "intent": intent,
                "params": template,
                "before": before_state if isinstance(before_state, dict) else {},
                "after": after_state if isinstance(after_state, dict) else {},
                "success": success,
                "error_code": error_code,
            }
            data.setdefault("executions", []).append(entry)
            # 只保留最近 200 条
            if len(data["executions"]) > 200:
                data["executions"] = data["executions"][-200:]

        # 更新统计
        stats = data.setdefault("stats", {})
        stats["total_motions"] = stats.get("total_motions", 0) + 1
        if not success:
            stats["errors"] = stats.get("errors", 0) + 1

        self._save(data)

    def cache_stats(self) -> dict:
        """返回缓存统计"""
        data = self._load()
        cache = data.get("semantic_cache", {})
        hot = sum(1 for v in cache.values() if v.get("frequency", 0) >= 5)
        total = len(cache)
        return {"total_intents": total, "hot_intents": hot, "hit_rate": round(hot / max(total, 1), 2)}

    @staticmethod
    def _normalize_intent(text: str) -> str:
        """标准化意图字符串: 去空格、统一方向词"""
        import re
        t = text.strip().lower()
        t = re.sub(r'\s+', '', t)
        # 统一方向语义
        synonyms = {
            '向上': '往上', '向上边': '往上', 'up': '往上',
            '向下': '往下', '向下边': '往下', 'down': '往下',
            '向左': '往左', 'left': '往左',
            '向右': '往右', 'right': '往右',
            '向前': '往前', 'forward': '往前',
            '向后': '往后', 'back': '往后',
        }
        for old, new in synonyms.items():
            t = t.replace(old, new)
        return t

    def get_knowledge_card(self) -> str:
        """生成一张经验卡片 — 给 Agent 做上下文"""
        data = self._load()
        stats = data.get("stats", {})
        patterns = data.get("patterns", [])
        recent = data["executions"][-5:]

        cache = data.get("semantic_cache", {})
        hot = sum(1 for v in cache.values() if v.get("frequency", 0) >= 5)
        card = "## ROCOS 经验累积\n\n"
        card += f"总动作: {stats.get('total_motions', 0)}  |  "
        card += f"错误: {stats.get('errors', 0)}  |  "
        card += f"恢复: {stats.get('recoveries', 0)}\n"
        card += f"语义缓存: {len(cache)} 个意图, {hot} 个高频命中\n\n"

        if patterns:
            card += "### 学到的模式\n"
            for p in sorted(patterns, key=lambda x: x.get("confidence", 0), reverse=True)[:5]:
                card += f"- [{p.get('confidence', 0):.0%}] {p.get('name', '')}: {p.get('advice', '')}\n"

        if recent:
            card += "\n### 最近动作\n"
            for e in reversed(recent[-3:]):
                ts = e.get("timestamp", "")[:19]
                card += f"- [{ts}] {e.get('action', '?')}: {e.get('summary', '')}\n"

        return card

class RocosReflect(Component):
    """分析历史记忆，提取模式和改进建议"""

    display_name: str = "ROCOS 经验自省"
    description: str = (
        "分析历史执行记录，自动发现模式: 哪些参数导致失败？哪些目标位置安全？"
        "Use this periodically to let the system learn from past actions."
    )
    icon: str = "BrainCircuit"
    name: str = "rocos_reflect"

    inputs = [
        StrInput(name="memory_dir", display_name="存储目录", value=DEFAULT_MEMORY_DIR, advanced=True),
    ]

    outputs = [
        Output(display_name="Tool", name="component_as_tool", method="to_tool",
            types=["Tool"], tool_mode=True),
    ]

    def to_tool(self) -> Tool:
        mdir = self.memory_dir
        def _run(_s: str = "") -> str:
            store = MemoryStore(os.path.join(mdir, DEFAULT_MEMORY_FILE))
            recent = store.get_recent(100); stats = store.get_stats()
            if not recent: return "暂无历史数据"
            errors = [e for e in recent if not e.get("success", True)]
            lines = [f"自省: {len(recent)}条记录, {len(errors)}错误, {stats.get('recoveries',0)}恢复"]
            if errors:
                from collections import Counter
                ea = Counter(e.get("action","?") for e in errors)
                for a, c in ea.most_common(3): lines.append(f"  高频错误: {a}×{c}")
            return "\n".join(lines)
        return Tool(name="ReflectMemory", description="分析历史执行记录，发现错误模式和趋势", func=_run)

    def analyze(self) -> Data:
        store = MemoryStore(os.path.join(self.memory_dir, DEFAULT_MEMORY_FILE))
        recent = store.get_recent(100)
        stats = store.get_stats()

        if not recent:
            return Data(text="暂无历史数据可供分析", data={"patterns": []})

        insights = []

        # 分析 1: 错误模式
        errors = [e for e in recent if not e.get("success", True)]
        if errors:
            # 统计错误前的动作类型
            from collections import Counter
            error_actions = Counter(e.get("action", "?") for e in errors)
            top_error = error_actions.most_common(1)[0]
            insights.append({
                "name": "高频错误动作",
                "advice": f"{top_error[0]} 出现了 {top_error[1]} 次错误，下次执行前先确认状态并降低速度",
                "confidence": min(0.9, top_error[1] / 5),
            })

        # 分析 2: 成功模式 — 最常用位置区域
        successes = [e for e in recent if e.get("success", True)]
        if successes:
            z_values = [e.get("state_snapshot", {}).get("flange_z", 0) for e in successes if "state_snapshot" in e]
            if z_values:
                avg_z = sum(z_values) / len(z_values)
                min_z, max_z = min(z_values), max(z_values)
                insights.append({
                    "name": "安全工作区间",
                    "advice": f"Z 轴安全区间: [{min_z:.3f}, {max_z:.3f}]，均值 {avg_z:.3f}。超出此范围时谨慎",
                    "confidence": 0.7,
                })

        # 分析 3: 恢复率
        if stats.get("errors", 0) > 0:
            recovery_rate = stats.get("recoveries", 0) / stats.get("errors", 0)
            if recovery_rate < 0.5:
                insights.append({
                    "name": "低恢复率",
                    "advice": "错误恢复率低，建议在 Agent 提示词中加入错误恢复流程指引",
                    "confidence": 0.8,
                })

        # 分析 4: 速度趋势
        velocities = []
        for e in recent:
            v = e.get("params", {}).get("velocity", 0)
            if v:
                velocities.append(v)
        if velocities:
            avg_vel = sum(velocities) / len(velocities)
            if avg_vel > 0.5:
                insights.append({
                    "name": "速度偏高",
                    "advice": f"平均速度 {avg_vel:.2f}，建议降低至 0.3 以下提高安全性",
                    "confidence": 0.6,
                })

        # 存储 pattern
        for ins in insights:
            store.add_pattern(ins)

        # 生成报告
        text = "## 自省分析报告\n\n"
        for ins in sorted(insights, key=lambda x: x["confidence"], reverse=True):
            text += f"- [{ins['confidence']:.0%}] {ins['name']}: {ins['advice']}\n"

        if not insights:
            text += "✅ 未发现明显模式，数据量可能不足。继续积累中...\n"

        text += f"\n分析样本: {len(recent)} 条记录"

        self.status = f"发现 {len(insights)} 个模式，覆盖 {len(recent)} 条记录"
        return Data(text=text, data={"patterns": insights, "stats": stats})
