"""RocosSafeExecutor Langflow component.

Generated by splitting _internal/rocos_agent.py because Langflow discovers one component per file.
"""

"""
ROCOS 语义层组件 — 将实战中迭代出的控制模式编码为可复用组件。

包含:
  - RocosAgentPrompt: 生成最优的 Agent 系统提示词
  - RocosErrorRecovery: 自动错误恢复
  - RocosSafeMoveL: 先读状态再执行 MoveL 的安全模式
  - ResetRobotFault: 复位机器人 Fault（POST /api/robot/reset）
"""

from langflow.custom import Component

from langflow.io import Output, StrInput, FloatInput, DropdownInput

from langflow.schema import Data, Message

from langchain_core.tools import Tool

import json

import time

import urllib.error

import urllib.parse

import urllib.request

from typing import Optional

def _error(code: int, message: str) -> dict:
    return {"success": False, "code": code, "message": message, "data": None}

def _url(base_url: str, path: str, params: Optional[dict] = None) -> str:
    url = f"{base_url.rstrip('/')}{path}"
    if params:
        query = urllib.parse.urlencode({k: v for k, v in params.items() if v is not None})
        if query:
            url = f"{url}?{query}"
    return url

def _decode_json(body: str) -> dict:
    if not body:
        return {}
    return json.loads(body)

def _parse_http_error(e: urllib.error.HTTPError) -> dict:
    try:
        body = e.read().decode("utf-8")
        parsed = _decode_json(body)
        if isinstance(parsed, dict):
            parsed.setdefault("success", False)
            parsed.setdefault("code", e.code)
            parsed.setdefault("message", e.reason)
            return parsed
    except Exception:
        pass
    return _error(e.code, f"HTTP {e.code}: {e.reason}")

def _rocos_request(
    base_url: str, path: str, method: str = "GET",
    body: Optional[dict] = None, params: Optional[dict] = None,
    expect_json: bool = True, timeout: float = 30.0,
):
    url = _url(base_url, path, params)
    data = json.dumps(body).encode("utf-8") if body is not None else None
    headers = {"Accept": "application/json" if expect_json else "*/*"}
    if data is not None:
        headers["Content-Type"] = "application/json"
    try:
        req = urllib.request.Request(url, data=data, headers=headers, method=method)
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            text = resp.read().decode("utf-8")
            return _decode_json(text) if expect_json else text
    except urllib.error.HTTPError as e:
        return _parse_http_error(e)
    except urllib.error.URLError as e:
        return _error(-1, f"网络错误: {e}")
    except json.JSONDecodeError as e:
        return _error(-2, f"JSON 解析错误: {e}")

def _rocos_get(base_url: str, path: str, params: Optional[dict] = None) -> dict:
    return _rocos_request(base_url, path, method="GET", params=params, timeout=10.0)

def _rocos_post(base_url: str, path: str, body: Optional[dict] = None) -> dict:
    return _rocos_request(base_url, path, method="POST", body=body or {})

def _rocos_delete(base_url: str, path: str, params: Optional[dict] = None) -> dict:
    return _rocos_request(base_url, path, method="DELETE", params=params)

def _rocos_text(base_url: str, path: str, params: Optional[dict] = None) -> str:
    return _rocos_request(base_url, path, method="GET", params=params, expect_json=False, timeout=10.0)

def parse_float_list(text: str, expected_len: Optional[int] = None) -> list[float]:
    values = [float(x.strip()) for x in text.split(",") if x.strip()]
    if expected_len is not None and len(values) != expected_len:
        raise ValueError(f"expected {expected_len} values, got {len(values)}")
    return values

DEFAULT_MEMORY_DIR = "/tmp/rocos_memory"

DEFAULT_MEMORY_FILE = "rocos_memory.json"
ACTION_TYPE_ALIASES = {
    "movej": "joint",
    "joint": "joint",
    "joint_move": "joint",
    "movel": "cartesian_delta",
    "cartesian": "cartesian_delta",
    "cartesian_delta": "cartesian_delta",
    "null": "nullspace",
    "nullspace": "nullspace",
    "svd": "svd",
    "svd_jog": "svd",
}

def _normalize_action(action: dict) -> dict:
    normalized = dict(action)
    raw_type = str(normalized.get("type", "")).strip().lower()
    normalized["type"] = ACTION_TYPE_ALIASES.get(raw_type, raw_type)
    return normalized

def _pos_distance(a: dict, b: dict) -> float:
    return (
        (a.get("x", 0.0) - b.get("x", 0.0)) ** 2
        + (a.get("y", 0.0) - b.get("y", 0.0)) ** 2
        + (a.get("z", 0.0) - b.get("z", 0.0)) ** 2
    ) ** 0.5

def _max_joint_error(a: list, b: list) -> float:
    if not a or not b:
        return float("inf")
    return max(abs(a[i] - b[i]) for i in range(min(len(a), len(b))))

def _max_joint_delta(a: list, b: list) -> float:
    if not a or not b:
        return 0.0
    return max(abs(a[i] - b[i]) for i in range(min(len(a), len(b))))

def _wait_move(base_url: str) -> dict:
    return _rocos_post(base_url, "/api/robot/wait_move", {})

def _extract_joints(state_data: dict) -> list:
    return [j["position"] for j in state_data.get("joint_states", [])]

def _verify_action(atype: str, action: dict, before_joints: list, after_joints: list,
                   after_pos: dict, target_pos: Optional[dict] = None,
                   joints_target: Optional[list] = None):
    if atype == "cartesian_delta":
        tolerance = action.get("verify_cartesian_tolerance", 0.005)
        error = _pos_distance(after_pos, target_pos or {})
        return error <= tolerance, f"cartesian_error={error:.6f}, tolerance={tolerance:.6f}"
    if atype == "joint":
        tolerance = action.get("verify_joint_tolerance", 0.005)
        error = _max_joint_error(after_joints, joints_target or [])
        return error <= tolerance, f"joint_error={error:.6f}, tolerance={tolerance:.6f}"
    if atype in ("nullspace", "svd"):
        min_delta = action.get("verify_min_joint_delta", 1e-4)
        delta = _max_joint_delta(before_joints, after_joints)
        return delta >= min_delta, f"max_joint_delta={delta:.6f}, min_delta={min_delta:.6f}"
    return True, ""

def _record_to_memory(memory_dir: str, entry: dict, intent: str = "", action_template: dict = None):
    """记录执行记忆 + 同步语义缓存（数据与 MemoryStore.cache_learn 兼容）"""
    import os as _os
    fpath = _os.path.join(memory_dir, DEFAULT_MEMORY_FILE)
    _os.makedirs(_os.path.dirname(fpath), exist_ok=True)
    if _os.path.exists(fpath):
        with open(fpath) as f:
            mem = json.load(f)
    else:
        mem = {"executions": [], "patterns": [], "semantic_cache": {},
               "stats": {"total_motions": 0, "errors": 0, "recoveries": 0}}

    # 1. 写执行记录（包含 before/after 状态, error_code）
    entry.setdefault("timestamp", time.strftime("%Y-%m-%dT%H:%M:%S"))
    mem.setdefault("executions", []).append(entry)
    if len(mem["executions"]) > 200:
        mem["executions"] = mem["executions"][-200:]

    # 2. 更新统计
    mem["stats"]["total_motions"] = mem["stats"].get("total_motions", 0) + 1
    if not entry.get("success", True):
        mem["stats"]["errors"] = mem["stats"].get("errors", 0) + 1

    # 3. 语义缓存学习（与 MemoryStore.cache_learn 相同格式）
    if intent and action_template:
        sc = mem.setdefault("semantic_cache", {})
        cache_key = intent.lower().replace(" ", "")
        ts = entry.get("timestamp", time.strftime("%Y-%m-%dT%H:%M:%S"))
        template_key = json.dumps(action_template, sort_keys=True)
        success = entry.get("success", True)

        if cache_key in sc and isinstance(sc[cache_key], dict):
            existing = sc[cache_key]
            if json.dumps(existing.get("action", {}), sort_keys=True) == template_key:
                existing["frequency"] = existing.get("frequency", 0) + 1
                if success:
                    existing["success_count"] = existing.get("success_count", 0) + 1
                else:
                    existing["failure_count"] = existing.get("failure_count", 0) + 1
                existing["last_used"] = ts
            else:
                existing["frequency"] = existing.get("frequency", 0) + 1
                existing["action"] = action_template
                if success:
                    existing["success_count"] = existing.get("success_count", 0) + 1
                else:
                    existing["failure_count"] = existing.get("failure_count", 0) + 1
        else:
            sc[cache_key] = {
                "action_name": "safe_executor",
                "action": action_template,
                "frequency": 1,
                "success_count": 1 if success else 0,
                "failure_count": 0 if success else 1,
                "first_seen": ts,
                "last_used": ts,
            }

    with open(fpath, 'w') as f:
        json.dump(mem, f, indent=2, ensure_ascii=False)

class RocosSafeExecutor(Component):
    """统一安全执行器: 读状态 → 校验 → 执行 → WaitMove → 自动记录

    接收结构化动作:
      {"type": "cartesian_delta", "frame": "BASE", "delta": [dx,dy,dz,0,0,0], "speed": 0.1}
      {"type": "joint", "joints": [0,1.047,...], "speed": 0.4}
      {"type": "nullspace", "joints_vec": [1,0,-1,0,0,0,0], "speed": 0.3, "timeout": 1.5}

    安全校验:
      - 机器人必须 STOPPED + enabled
      - 笛卡尔单步 ≤5cm
      - 关节单步 ≤0.3rad
      - 速度 ≤0.5
    """

    display_name: str = "ROCOS 安全执行器"
    description: str = (
        "统一的安全运动执行器。接收结构化动作描述，自动完成: "
        "1) 读状态 2) 安全检查 3) 执行 4) 等待完成 5) 自动记录记忆 6) 自动学习语义缓存。"
        "支持 cartesian_delta / joint / nullspace 三种动作类型。"
        "Use this as the single execution entry point for all robot motions."
    )
    icon: str = "ShieldCheck"
    name: str = "rocos_safe_executor"

    inputs = [
        StrInput(name="base_url", display_name="API 基础地址", value="http://localhost:8080"),
        StrInput(
            name="action_json",
            display_name="动作 (JSON)",
            info='{"type":"cartesian_delta","delta":[dx,dy,dz,0,0,0],"speed":0.1} or joint/nullspace',
            value='{"type":"cartesian_delta","delta":[0,0.03,0,0,0,0],"speed":0.1}',
        ),
        StrInput(name="intent", display_name="语义描述 (可选)", info='如"往右一点点", 用于缓存学习', value=""),
        StrInput(name="memory_dir", display_name="记忆目录", value="/tmp/rocos_memory", advanced=True),
    ]

    outputs = [
        Output(display_name="Tool", name="component_as_tool", method="to_tool",
            types=["Tool"], tool_mode=True),
    ]

    def to_tool(self) -> Tool:
        base = self.base_url
        default_action_json = self.action_json
        default_intent = self.intent
        memory_dir = self.memory_dir

        def _run(input_str: str = "") -> str:
            original_base = getattr(self, "base_url", base)
            original_action = getattr(self, "action_json", default_action_json)
            original_intent = getattr(self, "intent", default_intent)
            original_memory_dir = getattr(self, "memory_dir", memory_dir)

            action_json = default_action_json
            intent = default_intent
            raw = (input_str or "").strip()
            if raw:
                try:
                    parsed = json.loads(raw)
                    if isinstance(parsed, dict):
                        raw = parsed.get("__arg1", raw)
                        if "action_json" in parsed:
                            action_json = parsed["action_json"]
                        elif "action" in parsed:
                            action_json = parsed["action"]
                        intent = parsed.get("intent", intent)
                except json.JSONDecodeError:
                    pass
                if raw and action_json == default_action_json:
                    action_json = raw

            if isinstance(action_json, dict):
                action_json = json.dumps(action_json, ensure_ascii=False)

            try:
                self.base_url = base
                self.action_json = action_json
                self.intent = intent
                self.memory_dir = memory_dir
                result = self.execute()
                return result.text
            finally:
                self.base_url = original_base
                self.action_json = original_action
                self.intent = original_intent
                self.memory_dir = original_memory_dir

        return Tool(
            name="RocosSafeExecutor",
            description=(
                "安全执行机器人动作 JSON，并自动记录记忆。输入示例: "
                '{"type":"cartesian_delta","delta":[0,0.02,0,0,0,0],"speed":0.1}；'
                '{"type":"joint","joints":[...],"speed":0.3}；'
                '{"type":"nullspace","joints_vec":[1,0,-1,0,0,0,0],"speed":0.2,"timeout":2}'
            ),
            func=_run,
        )

    def execute(self) -> Data:
        import time, os, json as _json

        base = self.base_url.rstrip("/")
        memory_dir = self.memory_dir if self.memory_dir else DEFAULT_MEMORY_DIR

        # ---- Step 0: 解析动作 ----
        try:
            action = _json.loads(self.action_json)
        except _json.JSONDecodeError:
            return Data(text="EXECUTED=false\nreason=INVALID_ACTION_JSON\n❌ 动作 JSON 格式错误", data={"success": False})

        action = _normalize_action(action)
        atype = action.get("type", "")
        if atype not in ("cartesian_delta", "joint", "nullspace", "svd"):
            return Data(
                text=f"EXECUTED=false\nreason=UNSUPPORTED_ACTION_TYPE\n❌ 不支持的动作类型: {atype}，支持 cartesian_delta/joint/nullspace/svd",
                data={"success": False},
            )

        speed = action.get("speed", 0.15)

        # ---- Step 1: 读状态 ----
        state = _rocos_get(base, "/api/robot/state")
        sdata = state.get("data", {})
        robot_state = sdata.get("robot_state", "UNKNOWN")
        is_enabled = sdata.get("is_enabled", False)
        active_tool = sdata.get("active_tool_frame_name", "")
        active_object = sdata.get("active_object_frame_name", "")

        if robot_state != "STOPPED" or not is_enabled:
            text = f"❌ 机器人未就绪: state={robot_state}, enabled={is_enabled}"
            if robot_state == "ERROR_STATE":
                text += "\n💡 请先调用 ResetRobotFault 复位"
            self.status = text[:100]
            text = f"EXECUTED=false\nreason=ROBOT_NOT_READY\n{text}"
            return Data(text=text, data={
                "success": False, "state": robot_state,
                "active_tool": active_tool, "active_object": active_object,
            })

        flange = sdata.get("flange", {})
        before_pos = flange.get("position", {"x": 0, "y": 0, "z": 0})
        before_ori = flange.get("orientation", {"x": 0, "y": 0, "z": 0, "w": 1})
        joints_before = [j["position"] for j in sdata.get("joint_states", [])]

        # ---- Step 2: 安全检查 ----
        if speed > 0.5:
            return Data(text=f"EXECUTED=false\nreason=SPEED_LIMIT\n⛔ 速度 {speed} > 0.5，拒绝执行", data={"success": False, "rejected": True})

        if atype == "cartesian_delta":
            delta = action.get("delta", [0, 0, 0, 0, 0, 0])
            if len(delta) < 3:
                return Data(text="EXECUTED=false\nreason=INVALID_ACTION\n❌ cartesian_delta 需要至少3个元素 [dx,dy,dz]", data={"success": False})
            total = (delta[0]**2 + delta[1]**2 + delta[2]**2) ** 0.5
            if total > 0.05:
                return Data(text=f"EXECUTED=false\nreason=CARTESIAN_STEP_LIMIT\n⛔ 笛卡尔位移 {total*100:.1f}cm > 5cm，拒绝", data={"success": False, "rejected": True})
            if total == 0:
                return Data(text="EXECUTED=false\nreason=ZERO_MOTION\n⛔ 零位移，拒绝", data={"success": False, "rejected": True})

            # 构建 MoveL 目标
            target_pos = {
                "x": before_pos["x"] + delta[0],
                "y": before_pos["y"] + delta[1],
                "z": before_pos["z"] + delta[2],
            }
            result = _rocos_post(base, "/api/robot/movel", {
                "pose": {"position": target_pos, "orientation": before_ori},
                "velocity": speed,
            })
            api_path = "/api/robot/movel"

        elif atype == "joint":
            joints_target = action.get("joints", [])
            if not joints_target or len(joints_target) < 3:
                return Data(text="EXECUTED=false\nreason=INVALID_ACTION\n❌ joint 类型需要 joints 数组", data={"success": False})
            # 检查单步
            max_step = max(abs(joints_target[i] - joints_before[i]) for i in range(min(len(joints_target), len(joints_before))))
            if max_step > 0.3:
                return Data(text=f"EXECUTED=false\nreason=JOINT_STEP_LIMIT\n⛔ 关节单步 {max_step:.2f}rad > 0.3rad，拒绝", data={"success": False, "rejected": True})

            result = _rocos_post(base, "/api/robot/movej", {
                "joints": joints_target,
                "velocity": speed, "acceleration": 1.0,
            })
            api_path = "/api/robot/movej"

        elif atype == "nullspace":
            vec = action.get("joints_vec", [])
            timeout_s = action.get("timeout", 1.5)
            result = _rocos_post(base, "/api/robot/jog/nullspace", {
                "joints": vec, "direction": "POSITIVE",
                "speed": speed, "timeout": timeout_s,
            })
            api_path = "/api/robot/jog/nullspace"

        elif atype == "svd":
            result = _rocos_post(base, "/api/robot/jog/svd", {
                "dim_speeds": action.get("dim_speeds", action.get("speeds", [])),
                "timeout": action.get("timeout", 1.5),
                "dir_threshold": action.get("dir_threshold", 0.99),
            })
            api_path = "/api/robot/jog/svd"

        api_ok = result.get("success", False)
        api_code = result.get("code", 0)

        # ---- Step 3+4: 等待完成 + 读后状态 ----
        final_state = "UNKNOWN"
        wait_result = {"success": False, "code": 0, "message": "not called"}
        if api_ok:
            wait_result = _wait_move(base)
            final_state = wait_result.get("data", {}).get("robot_state", "UNKNOWN")

        after = {}
        adata = {}
        after_pos = {}
        joints_after = []
        verify_ok = False
        verify_reason = "not checked"
        verify_timeout = action.get("verify_timeout", 2.0)
        verify_interval = action.get("verify_interval", 0.05)
        verify_started = time.monotonic()
        while True:
            after = _rocos_get(base, "/api/robot/state")
            adata = after.get("data", {})
            final_state = adata.get("robot_state", final_state)
            after_pos = adata.get("flange", {}).get("position", {})
            joints_after = _extract_joints(adata)
            verify_ok, verify_reason = _verify_action(
                atype, action, joints_before, joints_after, after_pos,
                target_pos if atype == "cartesian_delta" else None,
                joints_target if atype == "joint" else None,
            )
            if verify_ok or final_state == "ERROR_STATE" or (time.monotonic() - verify_started) >= verify_timeout:
                break
            time.sleep(verify_interval)

        wait_ok = (not api_ok) or wait_result.get("success", False)
        success = api_ok and wait_ok and final_state == "STOPPED" and verify_ok

        # ---- Step 5: 自动记录 Memory ----
        entry = {
            "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S"),
            "action": atype,
            "params": action,
            "before": {
                "state": robot_state, "x": round(before_pos["x"], 4),
                "y": round(before_pos["y"], 4), "z": round(before_pos["z"], 4),
                "active_tool": active_tool, "active_object": active_object,
            },
            "after": {
                "state": final_state,
                "x": round(after_pos.get("x", 0), 4),
                "y": round(after_pos.get("y", 0), 4),
                "z": round(after_pos.get("z", 0), 4),
            },
            "success": success,
            "error_code": None if success else api_code,
            "wait_code": wait_result.get("code", 0),
            "verify_ok": verify_ok,
            "verify_reason": verify_reason,
        }
        # ---- Step 5+6: 记录记忆 + 缓存学习 ----
        intent = self.intent.strip()
        _record_to_memory(memory_dir, entry,
                          intent if (intent and success) else "",
                          action if (intent and success) else None)

        # ---- Step 7: 生成结果 ----
        if success:
            dx = round(after_pos.get("x", 0) - before_pos["x"], 4)
            dy = round(after_pos.get("y", 0) - before_pos["y"], 4)
            dz = round(after_pos.get("z", 0) - before_pos["z"], 4)
            text = (
                "EXECUTED=true\n"
                f"api_path={api_path}\n"
                f"api_code={api_code}\n"
                f"wait_code={wait_result.get('code', 0)}\n"
                f"final_state={final_state}\n"
                f"{verify_reason}\n"
                f"✅ {atype} 执行成功\n"
                f"位移: Δx={dx:.4f} Δy={dy:.4f} Δz={dz:.4f}\n"
                f"状态: {robot_state} → {final_state}\n"
                f"已自动记录记忆" + (f" + 缓存学习 '{intent}'" if intent else "")
            )
            freq = 0
        elif final_state == "ERROR_STATE":
            text = (
                "EXECUTED=false\n"
                f"api_path={api_path}\n"
                f"api_code={api_code}\n"
                f"wait_code={wait_result.get('code', 0)}\n"
                f"final_state={final_state}\n"
                f"❌ 执行失败 → ERROR_STATE (code={api_code})\n💡 请调用 ResetRobotFault 复位"
            )
        elif not wait_ok:
            text = (
                "EXECUTED=false\n"
                "reason=WAIT_MOVE_FAILED\n"
                f"api_path={api_path}\n"
                f"api_code={api_code}\n"
                f"wait_code={wait_result.get('code', 0)}\n"
                f"final_state={final_state}\n"
                f"❌ WaitMove 失败: {wait_result.get('message', '')}"
            )
        elif not verify_ok:
            text = (
                "EXECUTED=false\n"
                "reason=VERIFY_MOTION_FAILED\n"
                f"api_path={api_path}\n"
                f"api_code={api_code}\n"
                f"wait_code={wait_result.get('code', 0)}\n"
                f"final_state={final_state}\n"
                f"{verify_reason}\n"
                "❌ API/WaitMove 返回成功，但真实状态没有达到目标或没有检测到运动"
            )
        else:
            text = (
                "EXECUTED=false\n"
                f"api_path={api_path}\n"
                f"api_code={api_code}\n"
                f"wait_code={wait_result.get('code', 0)}\n"
                f"final_state={final_state}\n"
                f"❌ 执行失败 (code={api_code}): {result.get('message', '')}\n状态: {final_state}"
            )

        self.status = text[:100]
        return Data(text=text, data={
            "success": success, "state": final_state, "api_code": api_code,
            "before_pos": before_pos, "after_pos": after_pos,
            "before_joints": joints_before, "after_joints": joints_after,
            "wait_code": wait_result.get("code", 0),
            "verify_ok": verify_ok, "verify_reason": verify_reason,
            "memory_recorded": True,
        })
