"""RocosAgentPrompt Langflow component.

Generated by splitting _internal/rocos_agent.py because Langflow discovers one component per file.
"""

"""
ROCOS 语义层组件 — 将实战中迭代出的控制模式编码为可复用组件。

包含:
  - RocosAgentPrompt: 生成最优的 Agent 系统提示词
  - RocosErrorRecovery: 自动错误恢复
  - RocosSafeMoveL: 先读状态再执行 MoveL 的安全模式
  - ResetRobotFault: 复位机器人 Fault（POST /api/robot/reset）
"""

from langflow.custom import Component

from langflow.io import Output, StrInput, FloatInput, DropdownInput

from langflow.schema import Data, Message

from langchain_core.tools import Tool

import json

import urllib.error

import urllib.parse

import urllib.request

from typing import Optional

def _error(code: int, message: str) -> dict:
    return {"success": False, "code": code, "message": message, "data": None}

def _url(base_url: str, path: str, params: Optional[dict] = None) -> str:
    url = f"{base_url.rstrip('/')}{path}"
    if params:
        query = urllib.parse.urlencode({k: v for k, v in params.items() if v is not None})
        if query:
            url = f"{url}?{query}"
    return url

def _decode_json(body: str) -> dict:
    if not body:
        return {}
    return json.loads(body)

def _parse_http_error(e: urllib.error.HTTPError) -> dict:
    try:
        body = e.read().decode("utf-8")
        parsed = _decode_json(body)
        if isinstance(parsed, dict):
            parsed.setdefault("success", False)
            parsed.setdefault("code", e.code)
            parsed.setdefault("message", e.reason)
            return parsed
    except Exception:
        pass
    return _error(e.code, f"HTTP {e.code}: {e.reason}")

def _rocos_request(
    base_url: str, path: str, method: str = "GET",
    body: Optional[dict] = None, params: Optional[dict] = None,
    expect_json: bool = True, timeout: float = 30.0,
):
    url = _url(base_url, path, params)
    data = json.dumps(body).encode("utf-8") if body is not None else None
    headers = {"Accept": "application/json" if expect_json else "*/*"}
    if data is not None:
        headers["Content-Type"] = "application/json"
    try:
        req = urllib.request.Request(url, data=data, headers=headers, method=method)
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            text = resp.read().decode("utf-8")
            return _decode_json(text) if expect_json else text
    except urllib.error.HTTPError as e:
        return _parse_http_error(e)
    except urllib.error.URLError as e:
        return _error(-1, f"网络错误: {e}")
    except json.JSONDecodeError as e:
        return _error(-2, f"JSON 解析错误: {e}")

def _rocos_get(base_url: str, path: str, params: Optional[dict] = None) -> dict:
    return _rocos_request(base_url, path, method="GET", params=params, timeout=10.0)

def _rocos_post(base_url: str, path: str, body: Optional[dict] = None) -> dict:
    return _rocos_request(base_url, path, method="POST", body=body or {})

def _rocos_delete(base_url: str, path: str, params: Optional[dict] = None) -> dict:
    return _rocos_request(base_url, path, method="DELETE", params=params)

def _rocos_text(base_url: str, path: str, params: Optional[dict] = None) -> str:
    return _rocos_request(base_url, path, method="GET", params=params, expect_json=False, timeout=10.0)

def parse_float_list(text: str, expected_len: Optional[int] = None) -> list[float]:
    values = [float(x.strip()) for x in text.split(",") if x.strip()]
    if expected_len is not None and len(values) != expected_len:
        raise ValueError(f"expected {expected_len} values, got {len(values)}")
    return values

DEFAULT_MEMORY_DIR = "/tmp/rocos_memory"

DEFAULT_MEMORY_FILE = "rocos_memory.json"

def _record_to_memory(memory_dir: str, entry: dict, intent: str = "", action_template: dict = None):
    """记录执行记忆 + 同步语义缓存（数据与 MemoryStore.cache_learn 兼容）"""
    import os as _os
    fpath = _os.path.join(memory_dir, DEFAULT_MEMORY_FILE)
    _os.makedirs(_os.path.dirname(fpath), exist_ok=True)
    if _os.path.exists(fpath):
        with open(fpath) as f:
            mem = json.load(f)
    else:
        mem = {"executions": [], "patterns": [], "semantic_cache": {},
               "stats": {"total_motions": 0, "errors": 0, "recoveries": 0}}

    # 1. 写执行记录（包含 before/after 状态, error_code）
    entry.setdefault("timestamp", time.strftime("%Y-%m-%dT%H:%M:%S"))
    mem.setdefault("executions", []).append(entry)
    if len(mem["executions"]) > 200:
        mem["executions"] = mem["executions"][-200:]

    # 2. 更新统计
    mem["stats"]["total_motions"] = mem["stats"].get("total_motions", 0) + 1
    if not entry.get("success", True):
        mem["stats"]["errors"] = mem["stats"].get("errors", 0) + 1

    # 3. 语义缓存学习（与 MemoryStore.cache_learn 相同格式）
    if intent and action_template:
        sc = mem.setdefault("semantic_cache", {})
        cache_key = intent.lower().replace(" ", "")
        ts = entry.get("timestamp", time.strftime("%Y-%m-%dT%H:%M:%S"))
        template_key = json.dumps(action_template, sort_keys=True)
        success = entry.get("success", True)

        if cache_key in sc and isinstance(sc[cache_key], dict):
            existing = sc[cache_key]
            if json.dumps(existing.get("action", {}), sort_keys=True) == template_key:
                existing["frequency"] = existing.get("frequency", 0) + 1
                if success:
                    existing["success_count"] = existing.get("success_count", 0) + 1
                else:
                    existing["failure_count"] = existing.get("failure_count", 0) + 1
                existing["last_used"] = ts
            else:
                existing["frequency"] = existing.get("frequency", 0) + 1
                existing["action"] = action_template
                if success:
                    existing["success_count"] = existing.get("success_count", 0) + 1
                else:
                    existing["failure_count"] = existing.get("failure_count", 0) + 1
        else:
            sc[cache_key] = {
                "action_name": "safe_executor",
                "action": action_template,
                "frequency": 1,
                "success_count": 1 if success else 0,
                "failure_count": 0 if success else 1,
                "first_seen": ts,
                "last_used": ts,
            }

    with open(fpath, 'w') as f:
        json.dump(mem, f, indent=2, ensure_ascii=False)

class RocosAgentPrompt(Component):
    """生成 ROCOS 机器人控制 Agent 的最佳系统提示词"""

    display_name: str = "ROCOS Agent 提示词"
    description: str = (
        "生成经过实战迭代优化的 ROCOS 机器人控制 Agent 系统提示词。"
        "将此输出连接到 Agent 的 system_prompt 字段。"
        "包含: 先读状态再运动的模式、错误恢复流程、安全默认值、零空间语义。"
    )
    icon: str = "Brain"
    name: str = "rocos_agent_prompt"

    inputs = [
        StrInput(
            name="base_url",
            display_name="API 基础地址",
            info="ROCOS API 的基础 URL",
            value="http://localhost:8080",
        ),
        StrInput(
            name="robot_description",
            display_name="机器人描述",
            info="可选的机器人定制描述（型号、应用场景等）",
            value="7-DOF 机械臂，仿真模式",
        ),
    ]

    outputs = [
        Output(display_name="System Prompt", name="prompt", method="build_prompt",
            tool_mode=True),
    ]

    def build_prompt(self) -> Message:
        prompt = f"""你是 ROCOS 机器人控制助手。控制对象: {self.robot_description}。

## 核心规则 — 每次运动前必须遵守:

1. **先读状态再决策**: 调用 GetRobotState 获取真实的当前位置/姿态/状态
2. **基于真实坐标计算**: 不要假设机器人在上一次指令的目标位置，用 GetRobotState 返回的实际值
3. **小幅度执行**: 默认每次位移 ≤5cm，速度 ≤0.3
4. **错误恢复**: 如果 robot_state 是 ERROR_STATE，调 ResetRobotFault 复位

## 工作流程:
```
GetRobotState → 检查 STOPPED+enabled → 计算小幅度目标 → MoveJ/MoveL → 验证结果
```

## 状态码参考:
- STOPPED: 就绪，可以运动
- RUNNING: 运动中，等待完成
- ERROR_STATE: 需要复位 (调 ResetRobotFault 或 POST /api/robot/reset)
- 规划失败 (IK/限位) → 保持 STOPPED，调整目标重试
- 执行失败 (Fault) → ERROR_STATE → ResetRobotFault 复位

## API 参考:
- MoveJ: /api/robot/movej, 字段 joints(数组), velocity, acceleration, jerk
- MoveL: /api/robot/movel, 字段 pose(position+orientation), velocity
- 零空间SVD: /api/robot/jog/svd, 字段 dim_speeds([speed]单个标量), timeout(超时自动停) — 最简单的方式
- 坐标系: /api/robot/tool_frame, /api/robot/object_frame

## 安全守则:
- 不确定时用 MoveJ 比 MoveL 更安全（关节空间运动不会 IK 失败）
- 零空间运动前先读当前关节角度
- 接近目标点时缩小速度和步长
- Always respond in Chinese (简体中文)."""
        self.status = f"Prompt generated ({len(prompt)} chars)"
        return Message(text=prompt)
