"""RocosSafeMoveL Langflow component.

Generated by splitting _internal/rocos_agent.py because Langflow discovers one component per file.
"""

"""
ROCOS 语义层组件 — 将实战中迭代出的控制模式编码为可复用组件。

包含:
  - RocosAgentPrompt: 生成最优的 Agent 系统提示词
  - RocosErrorRecovery: 自动错误恢复
  - RocosSafeMoveL: 先读状态再执行 MoveL 的安全模式
  - ResetRobotFault: 复位机器人 Fault（POST /api/robot/reset）
"""

from langflow.custom import Component

from langflow.io import Output, StrInput, FloatInput, DropdownInput

from langflow.schema import Data, Message

from langchain_core.tools import Tool

import json

import urllib.error

import urllib.parse

import urllib.request

from typing import Optional

def _error(code: int, message: str) -> dict:
    return {"success": False, "code": code, "message": message, "data": None}

def _url(base_url: str, path: str, params: Optional[dict] = None) -> str:
    url = f"{base_url.rstrip('/')}{path}"
    if params:
        query = urllib.parse.urlencode({k: v for k, v in params.items() if v is not None})
        if query:
            url = f"{url}?{query}"
    return url

def _decode_json(body: str) -> dict:
    if not body:
        return {}
    return json.loads(body)

def _parse_http_error(e: urllib.error.HTTPError) -> dict:
    try:
        body = e.read().decode("utf-8")
        parsed = _decode_json(body)
        if isinstance(parsed, dict):
            parsed.setdefault("success", False)
            parsed.setdefault("code", e.code)
            parsed.setdefault("message", e.reason)
            return parsed
    except Exception:
        pass
    return _error(e.code, f"HTTP {e.code}: {e.reason}")

def _rocos_request(
    base_url: str, path: str, method: str = "GET",
    body: Optional[dict] = None, params: Optional[dict] = None,
    expect_json: bool = True, timeout: float = 30.0,
):
    url = _url(base_url, path, params)
    data = json.dumps(body).encode("utf-8") if body is not None else None
    headers = {"Accept": "application/json" if expect_json else "*/*"}
    if data is not None:
        headers["Content-Type"] = "application/json"
    try:
        req = urllib.request.Request(url, data=data, headers=headers, method=method)
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            text = resp.read().decode("utf-8")
            return _decode_json(text) if expect_json else text
    except urllib.error.HTTPError as e:
        return _parse_http_error(e)
    except urllib.error.URLError as e:
        return _error(-1, f"网络错误: {e}")
    except json.JSONDecodeError as e:
        return _error(-2, f"JSON 解析错误: {e}")

def _rocos_get(base_url: str, path: str, params: Optional[dict] = None) -> dict:
    return _rocos_request(base_url, path, method="GET", params=params, timeout=10.0)

def _rocos_post(base_url: str, path: str, body: Optional[dict] = None) -> dict:
    return _rocos_request(base_url, path, method="POST", body=body or {})

def _rocos_delete(base_url: str, path: str, params: Optional[dict] = None) -> dict:
    return _rocos_request(base_url, path, method="DELETE", params=params)

def _rocos_text(base_url: str, path: str, params: Optional[dict] = None) -> str:
    return _rocos_request(base_url, path, method="GET", params=params, expect_json=False, timeout=10.0)

def parse_float_list(text: str, expected_len: Optional[int] = None) -> list[float]:
    values = [float(x.strip()) for x in text.split(",") if x.strip()]
    if expected_len is not None and len(values) != expected_len:
        raise ValueError(f"expected {expected_len} values, got {len(values)}")
    return values

DEFAULT_MEMORY_DIR = "/tmp/rocos_memory"

DEFAULT_MEMORY_FILE = "rocos_memory.json"

def _record_to_memory(memory_dir: str, entry: dict, intent: str = "", action_template: dict = None):
    """记录执行记忆 + 同步语义缓存（数据与 MemoryStore.cache_learn 兼容）"""
    import os as _os
    fpath = _os.path.join(memory_dir, DEFAULT_MEMORY_FILE)
    _os.makedirs(_os.path.dirname(fpath), exist_ok=True)
    if _os.path.exists(fpath):
        with open(fpath) as f:
            mem = json.load(f)
    else:
        mem = {"executions": [], "patterns": [], "semantic_cache": {},
               "stats": {"total_motions": 0, "errors": 0, "recoveries": 0}}

    # 1. 写执行记录（包含 before/after 状态, error_code）
    entry.setdefault("timestamp", time.strftime("%Y-%m-%dT%H:%M:%S"))
    mem.setdefault("executions", []).append(entry)
    if len(mem["executions"]) > 200:
        mem["executions"] = mem["executions"][-200:]

    # 2. 更新统计
    mem["stats"]["total_motions"] = mem["stats"].get("total_motions", 0) + 1
    if not entry.get("success", True):
        mem["stats"]["errors"] = mem["stats"].get("errors", 0) + 1

    # 3. 语义缓存学习（与 MemoryStore.cache_learn 相同格式）
    if intent and action_template:
        sc = mem.setdefault("semantic_cache", {})
        cache_key = intent.lower().replace(" ", "")
        ts = entry.get("timestamp", time.strftime("%Y-%m-%dT%H:%M:%S"))
        template_key = json.dumps(action_template, sort_keys=True)
        success = entry.get("success", True)

        if cache_key in sc and isinstance(sc[cache_key], dict):
            existing = sc[cache_key]
            if json.dumps(existing.get("action", {}), sort_keys=True) == template_key:
                existing["frequency"] = existing.get("frequency", 0) + 1
                if success:
                    existing["success_count"] = existing.get("success_count", 0) + 1
                else:
                    existing["failure_count"] = existing.get("failure_count", 0) + 1
                existing["last_used"] = ts
            else:
                existing["frequency"] = existing.get("frequency", 0) + 1
                existing["action"] = action_template
                if success:
                    existing["success_count"] = existing.get("success_count", 0) + 1
                else:
                    existing["failure_count"] = existing.get("failure_count", 0) + 1
        else:
            sc[cache_key] = {
                "action_name": "safe_executor",
                "action": action_template,
                "frequency": 1,
                "success_count": 1 if success else 0,
                "failure_count": 0 if success else 1,
                "first_seen": ts,
                "last_used": ts,
            }

    with open(fpath, 'w') as f:
        json.dump(mem, f, indent=2, ensure_ascii=False)

class RocosSafeMoveL(Component):
    """先读取真实状态，再执行笛卡尔直线运动"""

    display_name: str = "安全 MoveL（先读后动）"
    description: str = (
        "安全的笛卡尔直线运动: 先自动读取机器人当前真实位姿，然后执行小幅度的 MoveL。"
        "delta_x/y/z 相对于当前位置的增量（米），推荐 ≤0.05m。"
        "Use this for safe, small incremental Cartesian movements. Automatically reads state first."
    )
    icon: str = "Shield"
    name: str = "rocos_safe_movel"

    inputs = [
        StrInput(
            name="base_url",
            display_name="API 基础地址",
            value="http://localhost:8080",
        ),
        FloatInput(
            name="delta_x",
            display_name="ΔX (m)",
            info="X 方向增量，正=前，负=后，推荐 ±0.03",
            value=0.0,
        ),
        FloatInput(
            name="delta_y",
            display_name="ΔY (m)",
            info="Y 方向增量，正=右，负=左，推荐 ±0.03",
            value=0.0,
        ),
        FloatInput(
            name="delta_z",
            display_name="ΔZ (m)",
            info="Z 方向增量，正=上，负=下，推荐 ±0.05",
            value=0.0,
        ),
        FloatInput(
            name="velocity",
            display_name="速度",
            info="运动速度，默认 0.15（慢速安全）",
            value=0.15,
        ),
    ]

    outputs = [
        Output(display_name="Move Result", name="result", method="safe_move",
            tool_mode=True),
    ]

    def safe_move(self) -> Data:
        base = self.base_url.rstrip("/")

        # Step 1: 读取真实状态
        state = _rocos_get(base, "/api/robot/state")
        sdata = state.get("data", {})

        robot_state = sdata.get("robot_state", "UNKNOWN")
        is_enabled = sdata.get("is_enabled", False)

        if robot_state != "STOPPED" or not is_enabled:
            text = f"❌ 机器人未就绪: state={robot_state}, enabled={is_enabled}"
            self.status = text
            return Data(text=text, data={"ready": False, "state": robot_state})

        flange = sdata.get("flange", {})
        current_pos = flange.get("position", {"x": 0, "y": 0, "z": 0})
        current_ori = flange.get("orientation", {"x": 0, "y": 0, "z": 0, "w": 1})

        # Step 2: 计算目标位姿（基于真实坐标 + 增量）
        target_pos = {
            "x": current_pos["x"] + self.delta_x,
            "y": current_pos["y"] + self.delta_y,
            "z": current_pos["z"] + self.delta_z,
        }

        # 安全检查: 位移超过 5cm 直接拒绝
        total_delta = (self.delta_x**2 + self.delta_y**2 + self.delta_z**2) ** 0.5
        if total_delta > 0.05:
            text = f"⛔ 安全限制: 单步位移 {total_delta*100:.1f}cm > 5cm，已拒绝。请减小步长。"
            self.status = text[:100]
            return Data(text=text, data={"rejected": True, "max_delta": 0.05, "requested": total_delta})

        # Step 3: 执行 MoveL
        result = _rocos_post(base, "/api/robot/movel", {
            "pose": {"position": target_pos, "orientation": current_ori},
            "velocity": self.velocity,
        })

        if result.get("success"):
            text = (
                f"✅ 安全 MoveL\n"
                f"当前 (真实): x={current_pos['x']:.4f} y={current_pos['y']:.4f} z={current_pos['z']:.4f}\n"
                f"目标:         x={target_pos['x']:.4f} y={target_pos['y']:.4f} z={target_pos['z']:.4f}\n"
                f"增量: Δx={self.delta_x:.4f} Δy={self.delta_y:.4f} Δz={self.delta_z:.4f}"
            )
        else:
            code = result.get("code", 0)
            text = f"❌ MoveL 失败 (code={code}): {result.get('message')}"
            if code == -2307:
                text += "\n💡 机器人进入 ERROR_STATE，请使用 'ROCOS 错误恢复' 工具"

        self.status = text[:100]
        return Data(text=text, data=result)
