"""SetWorkMode Langflow component.

Generated by splitting _internal/rocos_robot_control.py because Langflow discovers one component per file.
"""

"""
ROCOS 机器人基础控制 — Tool 模式。
EnableRobot / DisableRobot / SetWorkMode — 供 LLM Agent 调用。
"""

from langflow.custom import Component

from langflow.io import Output, StrInput, DropdownInput

from langchain_core.tools import Tool

import json as _json

import urllib.error as _urlerror

import urllib.request as _urlreq

from typing import Optional as _Optional

def _rocos_post(_base, _path, _body: dict):
    _url = f"{_base.rstrip('/')}{_path}"
    try:
        _data = _json.dumps(_body).encode("utf-8")
        _req = _urlreq.Request(_url, data=_data, headers={"Content-Type": "application/json", "Accept": "application/json"}, method="POST")
        with _urlreq.urlopen(_req, timeout=30) as _r:
            return _json.loads(_r.read().decode("utf-8"))
    except _urlerror.URLError as _e:
        return {"success": False, "code": -1, "message": f"err: {_e}", "data": None}
    except _json.JSONDecodeError as _e:
        return {"success": False, "code": -2, "message": f"json err: {_e}", "data": None}

WORK_MODES = ["position", "ee_admit_teach", "jnt_admit_teach", "jnt_imp", "cart_imp"]

class SetWorkMode(Component):
    display_name: str = "设置工作模式"
    description: str = "切换工作模式: position/ee_admit_teach/jnt_admit_teach/jnt_imp/cart_imp"
    icon: str = "Sliders"; name: str = "set_work_mode"
    inputs = [
        StrInput(name="base_url", value="http://localhost:8080"),
        DropdownInput(name="mode", options=WORK_MODES, value="position"),
    ]
    outputs = [Output(display_name="Tool", name="component_as_tool", method="to_tool", types=["Tool"], tool_mode=True)]

    def to_tool(self) -> Tool:
        base = self.base_url; mode = self.mode
        def _run(_s: str = "") -> str:
            r = _rocos_post(base, "/api/robot/workmode", {"mode": mode})
            return f"OK {mode}" if (r == {} or r.get("success", True)) else f"FAIL: {r.get('message')}"
        return Tool(name="SetWorkMode", description=f"切换工作模式为 {mode}", func=_run)
