"""UploadScript Langflow component.

Generated by splitting _internal/rocos_script.py because Langflow discovers one component per file.
"""

"""ROCOS Lua脚本管理 — Tool 模式。6个脚本管理组件"""

from langflow.custom import Component

from langflow.io import Output, StrInput

from langchain_core.tools import Tool

import json as _json

import urllib.request as _urlreq

def _post(b,p,d):
    bd=_json.dumps(d).encode()
    with _urlreq.urlopen(_urlreq.Request(f"{b.rstrip('/')}{p}",data=bd,headers={"Content-Type":"application/json","Accept":"application/json"},method="POST"),timeout=30) as r:
        return _json.loads(r.read().decode("utf-8"))

def _get(b,p):
    with _urlreq.urlopen(_urlreq.Request(f"{b.rstrip('/')}{p}",headers={"Accept":"application/json"}),timeout=10) as r:
        return _json.loads(r.read().decode("utf-8"))

BI=[StrInput(name="base_url",value="http://localhost:8080")]

TO=lambda m: [Output(display_name="Tool",name="component_as_tool",method=m,types=["Tool"],tool_mode=True)]

class UploadScript(Component):
    display_name="上传Lua脚本"; description="上传Lua源码到控制器内存"; icon="Upload"; name="upload_script"
    inputs=BI+[StrInput(name="filename",value="task.lua"),StrInput(name="source",value="robot.Sleep(100)")]
    outputs=TO("to_tool")
    def to_tool(self)->Tool:
        b,fn,src=self.base_url,self.filename,self.source
        def _run(s=""):
            r=_post(b,"/api/script/upload",{"filename":fn,"source":s if s.strip() else src})
            d=r.get("data",{}); return f"OK uploaded: id={d.get('script_id')} state={d.get('state')}" if r.get("success") else f"FAIL: {r.get('message')}"
        return Tool(name="UploadScript",description="上传并编译Lua脚本。参数: filename source",func=_run)
