// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_service.proto

#include "robot_service.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace rocos {
}  // namespace rocos
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_robot_5fservice_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_robot_5fservice_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_robot_5fservice_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_robot_5fservice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023robot_service.proto\022\005rocos\032\023robot_comm"
  "and.proto\032\021robot_state.proto\032\020robot_info"
  ".proto2\356\001\n\014RobotService\022D\n\rReadRobotInfo"
  "\022\027.rocos.RobotInfoRequest\032\030.rocos.RobotI"
  "nfoResponse\"\000\022G\n\016ReadRobotState\022\030.rocos."
  "RobotStateRequest\032\031.rocos.RobotStateResp"
  "onse\"\000\022O\n\022WriteRobotCommmand\022\032.rocos.Rob"
  "otCommandRequest\032\033.rocos.RobotCommandRes"
  "ponse\"\000B\023B\021RobotServiceProtob\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_robot_5fservice_2eproto_deps[3] = {
  &::descriptor_table_robot_5fcommand_2eproto,
  &::descriptor_table_robot_5finfo_2eproto,
  &::descriptor_table_robot_5fstate_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_robot_5fservice_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_robot_5fservice_2eproto = {
  false, false, 356, descriptor_table_protodef_robot_5fservice_2eproto, "robot_service.proto", 
  &descriptor_table_robot_5fservice_2eproto_once, descriptor_table_robot_5fservice_2eproto_deps, 3, 0,
  schemas, file_default_instances, TableStruct_robot_5fservice_2eproto::offsets,
  nullptr, file_level_enum_descriptors_robot_5fservice_2eproto, file_level_service_descriptors_robot_5fservice_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_robot_5fservice_2eproto_getter() {
  return &descriptor_table_robot_5fservice_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_robot_5fservice_2eproto(&descriptor_table_robot_5fservice_2eproto);
namespace rocos {

// @@protoc_insertion_point(namespace_scope)
}  // namespace rocos
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
